FROM debezium/connect:2.5.0.Final

ENV KAFKA_CONNECT_AVRO_DIR=$KAFKA_CONNECT_PLUGINS_DIR/kafka-connect-avro-converter
ENV CONFLUENT_VERSION=7.6.0

RUN mkdir -p $KAFKA_CONNECT_AVRO_DIR && \
    cd $KAFKA_CONNECT_AVRO_DIR && \
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-converter/$CONFLUENT_VERSION/kafka-connect-avro-converter-$CONFLUENT_VERSION.jar && \
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-connect-avro-data/$CONFLUENT_VERSION/kafka-connect-avro-data-$CONFLUENT_VERSION.jar && \
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/$CONFLUENT_VERSION/kafka-avro-serializer-$CONFLUENT_VERSION.jar && \
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-schema-serializer/$CONFLUENT_VERSION/kafka-schema-serializer-$CONFLUENT_VERSION.jar && \
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-schema-converter/$CONFLUENT_VERSION/kafka-schema-converter-$CONFLUENT_VERSION.jar && \
    curl -sO https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/$CONFLUENT_VERSION/kafka-schema-registry-client-$CONFLUENT_VERSION.jar && \
    curl -sO https://packages.confluent.io/maven/io/confluent/common-config/$CONFLUENT_VERSION/common-config-$CONFLUENT_VERSION.jar && \
    curl -sO https://packages.confluent.io/maven/io/confluent/common-utils/$CONFLUENT_VERSION/common-utils-$CONFLUENT_VERSION.jar && \
    curl -sO https://repo1.maven.org/maven2/org/apache/avro/avro/1.11.3/avro-1.11.3.jar && \
    curl -sO https://repo1.maven.org/maven2/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar && \
    curl -sO https://repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar